### ISSUE TITLE
Save doesn't work

### ISSUE THREAD

**Issue by MacNaab** [Bonkahe/DMmaps#1]
Hello,
I just noticed that save no longer work for one of my projects. Whether with CTRL + S or by File > Save Project.
Likewise if I use the Save Project As function (this saves the project but without my modifications).
This only happens for the elements where I modify text but not for the new ones created.

I noticed that if I use File > Load Project, it offers me to save and this time all the modifications are saved.

**Comment by Bonkahe** [comment]
Afirm, as soon as I'm able I will be on this to reproduce.

**Comment by Bonkahe** [comment]
Reproduced, working on a fix.

**Comment by Bonkahe** [comment]
Fix complete will be in next update later today, 0.8.7, if you re-encounter the bug let me know.

**Comment by MacNaab** [comment]
Thanks !! It's fixed
