### ISSUE TITLE
Search Result

### ISSUE THREAD

**Issue by MacNaab** [Bonkahe/DMmaps#12]
Hello, this is probably not a bug but when I search for an element and I click inside the search input, it directly removes the results:
![2020-11-17-21-58-03](https://user-images.githubusercontent.com/61412526/99449647-1f8da180-2920-11eb-905d-2504405176c4.gif)

**Comment by Bonkahe** [comment]
It was a bug, now it shouldn't clear unless you click out of the hierarchy panel.

Update has been pushed, also with a new icon.

**Comment by MacNaab** [comment]
This is fixed but now I noticed this (I don't know if it was present before or not):
![2020-11-18-00-07-18](https://user-images.githubusercontent.com/61412526/99461594-5ff61b00-2932-11eb-8ff2-f4fd2b95d5af.gif)

**Comment by MacNaab** [comment]
Fixed with last patch ! Thanks!
