### ISSUE TITLE
Display problem

### ISSUE THREAD

**Issue by MacNaab** [Bonkahe/DMmaps#2]
Hello,
I noticed that when we are not in full screen mode, and our text overflow, this causes a display problem (like the screen).
Note that this doesn't happen in full screen mode.

![image](https://user-images.githubusercontent.com/61412526/97088638-8e821e00-1632-11eb-88f5-dd5684ecfbd8.png)

**Comment by Bonkahe** [comment]
I actually know why it's doing this, have to reinstall visual studio (hard drive failure), I'll be back up and running some time shortly and I'll see if I can get it wrapped up.

**Comment by Bonkahe** [comment]
I am currently unable to reproduce this actually, could you possibly send me your dmdb?

(If your comfortable with that)

**Comment by MacNaab** [comment]
Sure ! Here's my save.

[Save.zip](https://github.com/Bonkahe/DMmaps/files/5433926/Save.zip)

Edit: This no longer causes the error, on the other hand the scroll bar only appears after switching to full screen mode.
You can try with Chapitre 1 or Chapitre 1 -> Personnages

**Comment by Bonkahe** [comment]
![DebugDmmaps](https://user-images.githubusercontent.com/11287274/97096299-ccca0e00-162f-11eb-950a-0b0d76538185.gif)
Hmmm this is the results I am getting, let me get a little info, please when experiencing the issue press ctrl+shift+i, and look in the top right, if there is a red message on the right please tell me what it is. Also what is your platform? (Operating system).

**Comment by MacNaab** [comment]
0 error in the console and now the scroll bar appears ! I'm on Windows 8.
Thank you for your quick support.
