### ISSUE TITLE
Drag & Drop

### ISSUE THREAD

**Issue by MacNaab** [Bonkahe/DMmaps#4]
Hello, it's me again. This time I made a little video to explain my problem:  
![2020-11-06 16-30-44 (online-video-cutter com)](https://user-images.githubusercontent.com/61412526/98384875-9be5d200-204e-11eb-95b1-587578665634.gif)  
I don't know if it's a bug or not (no error message in logs).

**Comment by Bonkahe** [comment]
Mmm yea that's a bug, would you be willing to send me your dmdb file?

**Comment by Bonkahe** [comment]
Correction, I was able to reproduce. Give me a bit.

**Comment by Bonkahe** [comment]
Bug fix should be in latest version allowing this functionality, it's being pushed out now. Not exactly a bug, and had to rework some of the backend, but it was functionality which should have been in there from the start, so all good. Check out the latest version if you get a chance.

**Comment by MacNaab** [comment]
Thank-you for your prompt response. Everything works fine, even on an old backup.
