### ISSUE TITLE
Creating document link bugs out text styling

### ISSUE THREAD

**Issue by Bonkahe** [Bonkahe/DMmaps#6]
![image](https://user-images.githubusercontent.com/11287274/98729050-ef626380-235f-11eb-8249-a5b0a67eb809.png)
Dragging a document into the text of another creates a functional link, but the text formatting is glitched.

**Comment by MacNaab** [comment]
Hello, is this a new feature? Or is it already present?

**Comment by Bonkahe** [comment]
> 
> 
> Hello, is this a new feature? Or is it already present?

It is a feature, should be fully functional in latest version, simply drag one document into another one, it will create a link which you can click to get to the linked document.
