### ISSUE TITLE
Do you really want to delete

### ISSUE THREAD

**Issue by MacNaab** [Bonkahe/DMmaps#7]
Hello, when I press the "delete" button while I am in a text area (the right part) I have the alert "Do you really want to delete".
There is nothing in logs, it is not really annoying since the "Backspace" key do the trick but I still wanted to inform you.
Well done for the latest updates, no problems there.
![image](https://user-images.githubusercontent.com/61412526/98917138-4f761880-24cc-11eb-8347-5822cf85092d.png)

**Comment by Bonkahe** [comment]
So pressing delete it thinks you want to delete the entire document, maybe I could make it so it only does that when you haven't got the text window selected?

**Comment by MacNaab** [comment]
Yeah that's it !

**Comment by Bonkahe** [comment]
Should have the necessary changes in the latest update.

**Comment by MacNaab** [comment]
Thanks! Everything works perfectly
