### ISSUE TITLE
Theme

### ISSUE THREAD

**Issue by MacNaab** [Bonkahe/DMmaps#9]
While I test your new features. I got this error when changing the "Hue slider tokens":
![error message](https://user-images.githubusercontent.com/61412526/99148043-d3273500-2685-11eb-80a2-00c49ab0472d.png)
Note: This error's popup is displayed multiple times.

BTW I was unable to try the "Broken Links" function because "Found no broken links."

**Comment by Bonkahe** [comment]
If you would navigate to C:\Users\ [ your username ] \AppData\Roaming\dmmaps\DmmapsSettings and retrieve the themesettings.json file, and post it here for me? I need to have a look at it if possible.

As a possible fix rename the file when your done to something else.

**Comment by MacNaab** [comment]
Sure! This is it:
[themesettings.zip](https://github.com/Bonkahe/DMmaps/files/5540914/themesettings.zip)

**Comment by Bonkahe** [comment]
Did changing it's name/deleting it help?
Also restart dmmaps after.

**Comment by MacNaab** [comment]
Now I have this error:
![image](https://user-images.githubusercontent.com/61412526/99149913-44201a00-2691-11eb-99a8-48b4b33fe9e8.png)

**Comment by Bonkahe** [comment]
Few questions, are you doing this in an empty database, and do any of the other theme tools work?
I'm a bit stumped on this, I have other reports of it working, let me check around and make sure everyone has it functional for them.

**Comment by MacNaab** [comment]
When I use it on an empty database I get the second error.
When opening a database, I have the second error then the first.
However, in both cases all other tools work without error. Moreover, despite the error, the tool seems to work correctly.
No error in the console.

**Comment by Bonkahe** [comment]
..... I have no idea what is going on. >.<

**Comment by MacNaab** [comment]
I noticed that it happened in the extremities of the slidebar, maybe this information can help

**Comment by MacNaab** [comment]
Small update here:
The problem only occurs when I move the slidebar.  When I use clicks it doesn't happen.
Looks like to add a ```}``` at the end of the .json.
When I edit this file and delete extra ```}```, no error when changing the "Hue slider tokens" value via click.

**Comment by Bonkahe** [comment]
Ok, pushing out some possible bug fixes for this. When update 0.11.4 goes live please let me know if it fixes your issues!

The } qued me in to what I think the issue might be, we'll see if I got it right.

**Comment by MacNaab** [comment]
No more issue with the last update ! Great job !
